Minor improvements of Russian localization
TinyModularThings/IC2Classic pull request #695
Opened 2023-03-14 16:19 UTC by CrossVas

This PR contains some improvements of Russian localization.
The wiki section is still WIP. Sorry, it requires a lot more polishing than I expected.

2023-03-15 10:51 UTC, cubicbyte requested changes
A couple of changes need to be made

2023-03-15 10:51 UTC, cubicbyte commented on src/main/resources/assets/ic2/lang/blocks_ru_ru.json
> +  "block.ic2.induction_furnace": "Индукционная плавильня",
This is better to be changed to Индукционная печь

2023-03-15 10:51 UTC, cubicbyte commented on src/main/resources/assets/ic2/lang/advancements_ru_ru.json
> +  "advancement.ic2.build_vacuum_canner.desc": "Создайте аакуумный консервирующий механизм",
There's a typo here

2023-03-15 19:57 UTC, Speiger commented
@CrossVas 
in the main language file this entry was added:
(en_us)
```
  "death.attack.radiation": "Radiated to death",
```

2023-03-15 23:18 UTC, CrossVas commented
@Speiger added new entry

2023-03-16 13:35 UTC, CrossVas commented
You think I should use the old translation?

2023-03-16 18:21 UTC, merged